# This workflow will push a release to NPM and GITHUB packages when there
# is a push to master, next and beta branches using semantic-release.
name: Release

on:
  push:
    branches:
      - master
      - next
      - beta
      - v[0-9]+.**

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: Install
        run: npm ci
      - name: Test
        run: npm test
      - name: Build
        run: npm run build:plugin
      - name: Publish
        run: npx semantic-release 
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
